### ISSUE TITLE
ipad air 9.0.2

### ISSUE THREAD

**Issue by brymonster** [Siguza/ios-kern-utils#10] opened 2017-03-05 21:20 UTC
recently trying to run `nvpatch` (experimental and master) im getting crashes. 
got it work a few days ago. but not anymore. of course running it after `./cl0ver`

**Comment by brymonster** [comment] 2017-03-05 21:27
my bad. wrong command. successful patch. still hangs at restore. 
`waiting for nonce: 56 33 79 b5 27 5c fd 07 66 76 93 f5 ff d6 2b 52 d9 27 2f 66`

**Comment by Siguza** [comment] 2017-03-05 21:30
Last I checked, you manually go to recovery mode before trying to restore, right? What if you _don't_ do that (futurerestore should do it automatically)? Maybe that "uses up" the first nonce...  
But as I've said before, probably the only one who can really help here is tihmstar.

**Comment by brymonster** [comment] 2017-03-05 21:31
[newest.txt](https://github.com/Siguza/ios-kern-utils/files/819762/newest.txt)

**Comment by brymonster** [comment] 2017-03-05 21:38
seems like the master kern utils worked out 1 of 5.

**Comment by brymonster** [comment] 2017-03-05 21:50
just as u suggested in normal mode. futurerestore will pop her into Recovery np. still no joy tho.
<img width="762" alt="screen shot 2017-03-05 at 1 46 25 pm" src="https://cloud.githubusercontent.com/assets/12586478/23591752/476e51fa-01aa-11e7-94b6-2f5a3a84051f.png">
weird joojoo with the generator i believe, when i first started trying this it would change, and then for a time it showed two, the valid one and target generator. now i just get the correct one.. all the time. but it doesnt work.

**Comment by Siguza** [comment] 2017-03-05 21:52
Uppercase. The `System` needs to be in uppercase. You're setting an NVRAM variable that no-one is looking for. -.-

    nvram com.apple.System.boot-nonce=0x16720224aed2294e

**Comment by brymonster** [comment] 2017-03-05 21:53
ive tried both. then why is my generator _always_ set? is that strange?

**Comment by brymonster** [comment] 2017-03-05 21:54
just rechecked my blobs. 
<img width="552" alt="screen shot 2017-03-05 at 1 52 24 pm" src="https://cloud.githubusercontent.com/assets/12586478/23591817/4439c504-01ab-11e7-81d7-28646f6bc50e.png">

**Comment by Siguza** [comment] 2017-03-05 21:58
What do you mean "always set"? You can set any NVRAM variable you like, e.g. `herp=derp` and it'll persist across reboots. Doesn't mean anyone's looking for them. Just get to it and use an uppercase S.

**Comment by brymonster** [comment] 2017-03-05 21:59
ok i was under the impression your had to set NVRAM every boot. mine persist thru reboots. thought it was strange. 
im working on it.

**Comment by brymonster** [comment] 2017-03-07 02:01
i changed the generator, then back to the correct one. started to restore!! but got error 11. 
n now my nonce is 'set' but i cant recreate the same success. 
`nvpatch com.apple.System.boot-nonce` is crashing my device everytime.. 
strange `boot-args` now too. 
>iBad:/var/mobile/Downloads/kern root# nvram -p
backlight-level	1607
com.apple.System.fp-state	%00%00%00%00`%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00
boot-args	rd=md0 nand-enable-reformat=1 -progress
auto-boot	true
com.apple.system.boot-nonce	0x16720224aed2294e

**Comment by Siguza** [comment] 2017-06-19 03:59
Alright, since restoring isn't my field and the technical issue is the same as in ticket #2, I'm closing this as a duplicate of it. If your issues with kern-utils persist, please comment on the other ticket.

**Closed by Siguza** 2017-06-19 03:59 UTC
